FROM ghc-7.10.3
WORKDIR /build-tmp
RUN apt-get install -y zlib1g-dev
RUN wget -q https://www.haskell.org/cabal/release/cabal-install-1.22.6.0/cabal-install-1.22.6.0.tar.gz && tar xf cabal-install-1.22.6.0.tar.gz && cd cabal-install-1.22.6.0 && ./bootstrap.sh

